version: "3.9"
services:
  micro_ros_agent:
    image: microros/micro-ros-agent:galactic
    stdin_open: true
    tty: true
    privileged: true
    network_mode: host
    volumes:
      - /dev:/dev
    command: serial --dev /dev/ttyACM0 -b 115200
    
  micro_ros_library_builder:
    image: microros/micro_ros_static_library_builder:galactic
    stdin_open: true
    tty: true
    privileged: true
    network_mode: host
    volumes:
      - "../:/project"